#import "../fragments/image.gql"
#import "../fragments/paintData.gql"

query PaintQuery($id: Id!) {
  paints {
    paint(id: $id) {
      id
      name
      description
      tags
      data {
        ...PaintDataFragment
      }
      createdById
      updatedAt
    }
  }
}
