query BadgesQuery {
  badges {
    badges {
      id
      name
      description
      tags
      images {
        ...ImageFragment
      }
      createdById
      updatedAt
      searchUpdatedAt
    }
  }
}
