query UserByConnection($platformId: String!) {
  users {
    userByConnection(platform: TWITCH, platformId: $platformId) {
      id
      emoteSets {
        id
        name
        kind
      }
    }
  }
}
