app:
  - 'src/foam/**'

website:
  - 'src/player-website/**'

proxy:
  - 'src/local-proxy/**'

Infrastructure:
  - 'infrastructure/**'
  - '.github/*'
  - '.github/**/*'

Documentation:
  - 'README.md'
