app:
  - changed-files:
      - any-glob-to-any-file:
          - '**/src/*'
          - '**/*.js'
          - '**/*.ts'
          - '**/*.tsx'

Infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - '**/terraform/*'
          - '**/terraform/**/*'
          - '.github/*'
          - '.github/**/*'
          - 'docker'

Documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
