const scopes = [
  'app',
  'ci',
  'test',
  'docs',
  'infrastructure',
  'chat',
  'twitch',
  'seventv',
  'bttv',
  'chat',
  'ffz',
  'stream',
  'auth',
  'tooling',
  'documentation',
  'security',
  'sentry',
  'monitoring',
  'firebase',
  'remote-config',
];

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [2, 'always', scopes],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'release',
      ],
    ],
  },
  scopeOverrides: {
    chore: [...scopes, { name: 'release' }],
  },
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix', 'perf', 'refactor', 'hotfix'],
  subjectLimit: 100,
  skipQuestions: ['body'],
};
