#import "../fragments/image.gql"
#import "../fragments/paintData.gql"

query PaintsQuery {
  paints {
    paints {
      id
      name
      description
      tags
      data {
        ...PaintDataFragment
      }
      createdById
      updatedAt
    }
  }
}
