import type { SanitisedEmote } from '@app/types/emote';

export const ffzSanitisedGlobalEmoteSet: SanitisedEmote[] = [
  {
    name: 'ZrehplaR',
    id: '9',
    url: 'https://cdn.frankerfacez.com/emote/9/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/9',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'YooHoo',
    id: '6',
    url: 'https://cdn.frankerfacez.com/emote/6/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/6',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'ManChicken',
    id: '4',
    url: 'https://cdn.frankerfacez.com/emote/4/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/4',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'BeanieHipster',
    id: '3',
    url: 'https://cdn.frankerfacez.com/emote/3/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/3',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'CatBag',
    id: '25927',
    url: 'https://cdn.frankerfacez.com/emote/25927/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/25927',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'ZreknarF',
    id: '27081',
    url: 'https://cdn.frankerfacez.com/emote/27081/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/27081',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'LilZ',
    id: '28136',
    url: 'https://cdn.frankerfacez.com/emote/28136/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/28136',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'ZliL',
    id: '28138',
    url: 'https://cdn.frankerfacez.com/emote/28138/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/28138',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'LaterSooner',
    id: '149346',
    url: 'https://cdn.frankerfacez.com/emote/149346/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/149346',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'BORT',
    id: '142673',
    url: 'https://cdn.frankerfacez.com/emote/142673/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/142673',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
  {
    name: 'BibleThump',
    id: '757384',
    url: 'https://cdn.frankerfacez.com/emote/757384/4',
    emote_link: 'https://www.frankerfacez.com/emoticon/757384',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 28,
    aspect_ratio: 1,
  },
];
