import { theme } from '@app/styles/themes';

const IMAGE_ASPECT_RATIO = 110 / 155;

export const CATEGORY_CARD_IMAGE_HEIGHT = 150;

export const CATEGORY_CARD_IMAGE_WIDTH =
  CATEGORY_CARD_IMAGE_HEIGHT * IMAGE_ASPECT_RATIO;

const IMAGE_SOURCE_SCALE = 2;

export const IMAGE_SOURCE_WIDTH = Math.round(
  CATEGORY_CARD_IMAGE_WIDTH * IMAGE_SOURCE_SCALE,
);

export const IMAGE_SOURCE_HEIGHT =
  CATEGORY_CARD_IMAGE_HEIGHT * IMAGE_SOURCE_SCALE;

export const TITLE_LINE_HEIGHT = 24;
export const TITLE_MAX_LINES = 2;

export const CATEGORY_CARD_TITLE_HEIGHT = TITLE_LINE_HEIGHT * TITLE_MAX_LINES;

export const CATEGORY_CARD_HEIGHT =
  CATEGORY_CARD_IMAGE_HEIGHT +
  theme.space12 +
  CATEGORY_CARD_TITLE_HEIGHT +
  theme.space16;
