// Generated by scripts/generateEmojiDataset.mjs (bun run gen:emoji) so the
// raw emojibase-data JSON (~1.1MB) stays out of the app bundle.
import type { EmojiSanitisedEmote } from '@app/types/emote';
import { createEmoteImageVariants } from '@app/utils/emote/emoteImageVariants/createEmoteImageVariants';

import emojiDataset from '@app/utils/emoji/emojiDataset.json';

export type EmojiStyle = 'twitter' | 'google';

const EMOJI_CDN_BY_STYLE: Record<EmojiStyle, (hexcode: string) => string> = {
  twitter: hexcode =>
    `https://cdn.jsdelivr.net/gh/jdecked/twemoji@16.0.1/assets/72x72/${hexcode.toLowerCase()}.png`,
  google: hexcode =>
    `https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/72/emoji_u${hexcode.toLowerCase()}.png`,
};

export const EMOJI_STYLE_OPTIONS: {
  label: string;
  value: EmojiStyle;
}[] = [
  { label: 'Twitter', value: 'twitter' },
  { label: 'Google', value: 'google' },
];

function createEmojiEmote(
  hexcode: string,
  alias: string,
  style: EmojiStyle,
): EmojiSanitisedEmote {
  const shortcode = `:${alias}:`;
  const url = EMOJI_CDN_BY_STYLE[style](hexcode);
  const imageVariants = createEmoteImageVariants({
    animated: {
      '4x': url,
    },
    static: {
      '4x': url,
    },
  });

  return {
    id: `${hexcode}:${alias}`,
    name: shortcode,
    original_name: shortcode,
    emoji_hexcode: hexcode,
    creator: null,
    emote_link: '',
    url,
    static_url: url,
    image_variants: imageVariants,
    site: 'Emoji',
    width: 72,
    height: 72,
    aspect_ratio: 1,
    zero_width: false,
  };
}

const emojiEmoteCache = new Map<EmojiStyle, EmojiSanitisedEmote[]>();

export function getEmojiEmotes(style: EmojiStyle): EmojiSanitisedEmote[] {
  const cached = emojiEmoteCache.get(style);
  if (cached) {
    return cached;
  }

  const emotes = (emojiDataset as [string, string[]][]).flatMap(
    ([hexcode, aliases]) =>
      aliases.map(alias => createEmojiEmote(hexcode, alias, style)),
  );

  emojiEmoteCache.set(style, emotes);
  return emotes;
}
