import { StyleSheet } from 'react-native';

import { theme } from '@app/styles/themes';

const MENU_BACKGROUND = theme.color.menu.background;
const MENU_HEADER_BACKGROUND = theme.color.menu.header;
const MENU_CARD = theme.color.menu.card;
const MENU_CARD_ACTIVE = theme.color.menu.cardActive;
const MENU_BORDER = theme.color.menu.border;
const MENU_BORDER_ACTIVE = theme.color.menu.borderActive;

export const emoteSheetStyles = StyleSheet.create({
  body: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
    width: '100%',
  },
  categoryBar: {
    alignItems: 'center',
    backgroundColor: MENU_HEADER_BACKGROUND,
    borderTopColor: MENU_BORDER,
    borderTopWidth: 1,
    flexDirection: 'row',
    overflow: 'hidden',
    paddingTop: theme.space8,
    width: '100%',
  },
  categoryBarContent: {
    alignItems: 'center',
    gap: theme.space8,
    paddingHorizontal: theme.space12,
  },
  container: {
    alignSelf: 'stretch',
    backgroundColor: MENU_BACKGROUND,
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    width: '100%',
  },
  sheetHandle: {
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 999,
    height: 5,
    width: 36,
  },
  sheetHandleRow: {
    alignItems: 'center',
    backgroundColor: MENU_HEADER_BACKGROUND,
    justifyContent: 'center',
    paddingBottom: 4,
    paddingTop: 8,
    width: '100%',
  },
  emojiText: {
    lineHeight: undefined,
  },
  emoteCell: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 8,
    justifyContent: 'center',
    padding: 3,
  },
  emoteRow: {
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'flex-start',
    paddingVertical: 2,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.space28,
    paddingTop: theme.space56,
  },
  emptyStateBody: {
    color: theme.color.textSecondary.dark,
    fontSize: theme.fontSize14,
    marginTop: theme.space12,
    textAlign: 'center',
  },
  emptyStateTitle: {
    fontSize: theme.fontSize18,
    fontWeight: '700',
  },
  header: {
    backgroundColor: MENU_HEADER_BACKGROUND,
    borderBottomColor: MENU_BORDER,
    borderBottomWidth: 1,
    minHeight: 102,
    overflow: 'hidden',
    paddingBottom: theme.space8,
    position: 'relative',
    width: '100%',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: theme.space36,
    paddingHorizontal: 16,
    paddingTop: theme.space4,
  },
  placeholderContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 420,
  },
  providerBar: {
    maxHeight: 54,
  },
  providerBarContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.space12,
    paddingHorizontal: theme.space16,
    paddingVertical: theme.space8,
  },
  providerChip: {
    alignItems: 'center',
    backgroundColor: MENU_CARD,
    borderColor: MENU_BORDER,
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: theme.space8,
    height: 38,
    justifyContent: 'center',
    minWidth: 40,
    paddingHorizontal: theme.space12,
    position: 'relative',
  },
  providerChipActive: {
    backgroundColor: MENU_CARD_ACTIVE,
    borderColor: MENU_BORDER_ACTIVE,
    minWidth: 88,
    paddingHorizontal: theme.space12,
  },
  providerChipIcon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  providerChipTitle: {
    color: theme.color.text.dark,
    fontSize: theme.fontSize12,
    fontWeight: '700',
  },
  searchContainer: {
    height: 48,
    justifyContent: 'center',
    marginTop: theme.space12,
    paddingHorizontal: theme.space16,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  searchInputWrap: {
    alignItems: 'center',
    backgroundColor: MENU_CARD,
    borderColor: MENU_BORDER,
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    flexDirection: 'row',
    gap: theme.space8,
    minHeight: 40,
    paddingHorizontal: theme.space12,
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    color: theme.color.text.dark,
    flex: 1,
    fontSize: theme.fontSize16,
    fontWeight: '500',
    height: 40,
    minHeight: 40,
    paddingHorizontal: 0,
  },
  searchIcon: {
    color: theme.color.textSecondary.dark,
    opacity: 0.7,
  },
  searchClearButton: {
    alignItems: 'center',
    backgroundColor: MENU_CARD_ACTIVE,
    borderRadius: 4,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  searchClearButtonHidden: {
    opacity: 0,
    pointerEvents: 'none',
  },
  setHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.space8,
    marginBottom: theme.space4,
    marginTop: theme.space8,
    minHeight: 36,
    paddingHorizontal: theme.space4,
    paddingVertical: theme.space4,
  },
  setHeaderIcon: {
    alignItems: 'center',
    borderRadius: 4,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  setHeaderTitle: {
    color: theme.color.textSecondary.dark,
    flex: 1,
    fontSize: theme.fontSize12,
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  setRailAvatar: {
    borderRadius: 12,
    height: 24,
    width: 24,
  },
  setRailAvatarContainer: {
    borderRadius: 12,
    height: 24,
    overflow: 'hidden',
    width: 24,
  },
  setRailButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderCurve: 'continuous',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    minWidth: 40,
    paddingHorizontal: theme.space8,
  },
  setRailButtonActive: {
    backgroundColor: MENU_CARD_ACTIVE,
  },
  setRailEmoji: {
    fontSize: theme.fontSize16,
  },
  setRailLabel: {
    color: 'rgba(255, 255, 255, 0.62)',
    fontSize: theme.fontSize10,
    fontWeight: '800',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  setRailLabelActive: {
    color: theme.color.text.dark,
  },
});
