import { StyleSheet } from 'react-native';

import { theme } from '@app/styles/themes';

const MENU_HEADER_BACKGROUND = '#111215';
const MENU_BORDER = 'rgba(255, 255, 255, 0.075)';

export const emoteSheetStyles = StyleSheet.create({
  body: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
    width: '100%',
  },
  categoryBar: {
    alignItems: 'center',
    backgroundColor: MENU_HEADER_BACKGROUND,
    borderTopColor: MENU_BORDER,
    borderTopWidth: 1,
    flexDirection: 'row',
    overflow: 'hidden',
    paddingTop: theme.space8,
    width: '100%',
  },
  categoryBarContent: {
    alignItems: 'center',
    gap: theme.space8,
    paddingHorizontal: theme.space12,
  },
  container: {
    alignSelf: 'stretch',
    backgroundColor: '#0b0b0d',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    width: '100%',
  },
  sheetHandle: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 999,
    height: 5,
    width: 36,
  },
  sheetHandleRow: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 4,
    paddingTop: 8,
    width: '100%',
  },
  emojiIconText: {
    fontSize: theme.fontSize18,
  },
  emojiText: {
    lineHeight: undefined,
  },
  emoteCell: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 8,
    justifyContent: 'center',
    padding: 3,
  },
  emoteCellInner: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  emoteImage: {
    alignSelf: 'center',
  },
  emoteImageContainer: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emoteImageLoading: {
    opacity: 0,
  },
  emoteImagePlaceholder: {
    backgroundColor: '#202127',
    borderColor: 'rgba(255,255,255,0.055)',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  emoteImageShimmer: {
    opacity: 0.9,
  },
  emoteRow: {
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'flex-start',
    paddingVertical: 2,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.space28,
    paddingTop: theme.space56,
  },
  emptyStateBody: {
    color: theme.color.textSecondary.dark,
    fontSize: theme.fontSize14,
    marginTop: theme.space12,
    textAlign: 'center',
  },
  emptyStateTitle: {
    fontSize: theme.fontSize18,
    fontWeight: '700',
  },
  fallbackIconLabel: {
    color: theme.color.textSecondary.dark,
    fontSize: theme.fontSize11,
    fontWeight: '800',
    letterSpacing: 0,
  },
  ffzTextIcon: {
    color: theme.colorPrimary,
    letterSpacing: 0,
  },
  ffzTextIconActive: {
    color: theme.color.text.dark,
  },
  header: {
    backgroundColor: MENU_HEADER_BACKGROUND,
    borderBottomColor: MENU_BORDER,
    borderBottomWidth: 1,
    minHeight: 102,
    overflow: 'hidden',
    paddingBottom: theme.space8,
    position: 'relative',
    width: '100%',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: theme.space36,
    paddingHorizontal: 16,
    paddingTop: theme.space4,
  },
  placeholderContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 420,
  },
  providerBar: {
    maxHeight: 54,
  },
  providerBarContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.space12,
    paddingHorizontal: theme.space16,
    paddingVertical: theme.space8,
  },
  providerChip: {
    alignItems: 'center',
    backgroundColor: '#191a1f',
    borderColor: 'rgba(255,255,255,0.055)',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: theme.space8,
    height: 38,
    justifyContent: 'center',
    minWidth: 40,
    paddingHorizontal: theme.space12,
    position: 'relative',
  },
  providerChipActive: {
    backgroundColor: 'rgba(46,134,255,0.18)',
    borderColor: 'rgba(46,134,255,0.4)',
    minWidth: 88,
    paddingHorizontal: theme.space12,
  },
  providerChipIcon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  providerChipTitle: {
    color: theme.color.text.dark,
    fontSize: theme.fontSize12,
    fontWeight: '700',
  },
  searchContainer: {
    height: 48,
    justifyContent: 'center',
    marginTop: theme.space12,
    paddingHorizontal: theme.space16,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  searchInputWrap: {
    alignItems: 'center',
    backgroundColor: '#1f2025',
    borderColor: 'rgba(255,255,255,0.065)',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    flexDirection: 'row',
    gap: theme.space8,
    minHeight: 40,
    paddingHorizontal: theme.space12,
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    color: theme.color.text.dark,
    flex: 1,
    fontSize: theme.fontSize16,
    fontWeight: '500',
    height: 40,
    minHeight: 40,
    paddingHorizontal: 0,
  },
  searchIcon: {
    color: theme.color.textSecondary.dark,
    opacity: 0.7,
  },
  searchClearButton: {
    alignItems: 'center',
    backgroundColor: '#2b2d33',
    borderRadius: 4,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  searchClearButtonHidden: {
    opacity: 0,
    pointerEvents: 'none',
  },
  setHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.space8,
    marginBottom: theme.space4,
    marginTop: theme.space8,
    minHeight: 36,
    paddingHorizontal: theme.space4,
    paddingVertical: theme.space4,
  },
  setHeaderIcon: {
    alignItems: 'center',
    borderRadius: 4,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  setHeaderTitle: {
    color: theme.color.text.dark,
    flex: 1,
    fontSize: theme.fontSize14,
    fontWeight: '600',
    letterSpacing: 0,
  },
  setRailButton: {
    alignItems: 'center',
    backgroundColor: '#191a1f',
    borderColor: 'rgba(255,255,255,0.045)',
    borderCurve: 'continuous',
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: 'center',
    minWidth: 40,
    paddingHorizontal: theme.space8,
  },
  setRailButtonActive: {
    backgroundColor: 'rgba(46,134,255,0.18)',
    borderColor: 'rgba(46,134,255,0.4)',
  },
  setRailEmoji: {
    fontSize: theme.fontSize16,
  },
  setRailLabel: {
    color: 'rgba(255, 255, 255, 0.62)',
    fontSize: theme.fontSize10,
    fontWeight: '800',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  setRailLabelActive: {
    color: theme.color.text.dark,
  },
});
