import type { FfzSanitisedEmote } from '@app/types/emote';

export const ffzSanitisedGlobalEmoteSet: FfzSanitisedEmote[] = [
  {
    name: 'ZrehplaR',
    id: '9',
    url: 'https://cdn.frankerfacez.com/emote/9/4',
    static_url: 'https://cdn.frankerfacez.com/emote/9/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/9/4',
        '2x': 'https://cdn.frankerfacez.com/emote/9/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/9/4',
        '2x': 'https://cdn.frankerfacez.com/emote/9/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/9',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 33,
    height: 30,
    aspect_ratio: 1.1,
  },
  {
    name: 'YooHoo',
    id: '6',
    url: 'https://cdn.frankerfacez.com/emote/6/4',
    static_url: 'https://cdn.frankerfacez.com/emote/6/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/6/4',
        '2x': 'https://cdn.frankerfacez.com/emote/6/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/6/4',
        '2x': 'https://cdn.frankerfacez.com/emote/6/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/6',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 34,
    aspect_ratio: 0.8235294117647058,
  },
  {
    name: 'ManChicken',
    id: '4',
    url: 'https://cdn.frankerfacez.com/emote/4/4',
    static_url: 'https://cdn.frankerfacez.com/emote/4/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/4/4',
        '2x': 'https://cdn.frankerfacez.com/emote/4/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/4/4',
        '2x': 'https://cdn.frankerfacez.com/emote/4/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/4',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 30,
    height: 29,
    aspect_ratio: 1.0344827586206897,
  },
  {
    name: 'BeanieHipster',
    id: '3',
    url: 'https://cdn.frankerfacez.com/emote/3/4',
    static_url: 'https://cdn.frankerfacez.com/emote/3/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/3/4',
        '2x': 'https://cdn.frankerfacez.com/emote/3/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/3/4',
        '2x': 'https://cdn.frankerfacez.com/emote/3/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/3',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 28,
    height: 33,
    aspect_ratio: 0.8484848484848485,
  },
  {
    name: 'CatBag',
    id: '25927',
    url: 'https://cdn.frankerfacez.com/emote/25927/4',
    static_url: 'https://cdn.frankerfacez.com/emote/25927/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/25927/4',
        '2x': 'https://cdn.frankerfacez.com/emote/25927/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/25927/4',
        '2x': 'https://cdn.frankerfacez.com/emote/25927/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/25927',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 32,
    height: 29,
    aspect_ratio: 1.103448275862069,
  },
  {
    name: 'ZreknarF',
    id: '27081',
    url: 'https://cdn.frankerfacez.com/emote/27081/4',
    static_url: 'https://cdn.frankerfacez.com/emote/27081/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/27081/4',
        '2x': 'https://cdn.frankerfacez.com/emote/27081/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/27081/4',
        '2x': 'https://cdn.frankerfacez.com/emote/27081/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/27081',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 40,
    height: 30,
    aspect_ratio: 1.3333333333333333,
  },
  {
    name: 'LilZ',
    id: '28136',
    url: 'https://cdn.frankerfacez.com/emote/28136/4',
    static_url: 'https://cdn.frankerfacez.com/emote/28136/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/28136/4',
        '2x': 'https://cdn.frankerfacez.com/emote/28136/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/28136/4',
        '2x': 'https://cdn.frankerfacez.com/emote/28136/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/28136',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 32,
    height: 23,
    aspect_ratio: 1.391304347826087,
  },
  {
    name: 'ZliL',
    id: '28138',
    url: 'https://cdn.frankerfacez.com/emote/28138/4',
    static_url: 'https://cdn.frankerfacez.com/emote/28138/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/28138/4',
        '2x': 'https://cdn.frankerfacez.com/emote/28138/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/28138/4',
        '2x': 'https://cdn.frankerfacez.com/emote/28138/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/28138',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 32,
    height: 23,
    aspect_ratio: 1.391304347826087,
  },
  {
    name: 'LaterSooner',
    id: '149346',
    url: 'https://cdn.frankerfacez.com/emote/149346/4',
    static_url: 'https://cdn.frankerfacez.com/emote/149346/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/149346/4',
        '2x': 'https://cdn.frankerfacez.com/emote/149346/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/149346/4',
        '2x': 'https://cdn.frankerfacez.com/emote/149346/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/149346',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 25,
    height: 32,
    aspect_ratio: 0.78125,
  },
  {
    name: 'BORT',
    id: '142673',
    url: 'https://cdn.frankerfacez.com/emote/142673/4',
    static_url: 'https://cdn.frankerfacez.com/emote/142673/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/142673/4',
        '2x': 'https://cdn.frankerfacez.com/emote/142673/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/142673/4',
        '2x': 'https://cdn.frankerfacez.com/emote/142673/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/142673',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 19,
    height: 30,
    aspect_ratio: 0.6333333333333333,
  },
  {
    name: 'BibleThump',
    id: '757384',
    url: 'https://cdn.frankerfacez.com/emote/757384/4',
    static_url: 'https://cdn.frankerfacez.com/emote/757384/4',
    image_variants: {
      animated: {
        '4x': 'https://cdn.frankerfacez.com/emote/757384/4',
        '2x': 'https://cdn.frankerfacez.com/emote/757384/2',
      },
      static: {
        '4x': 'https://cdn.frankerfacez.com/emote/757384/4',
        '2x': 'https://cdn.frankerfacez.com/emote/757384/2',
      },
    },
    emote_link: 'https://www.frankerfacez.com/emoticon/757384',
    creator: 'UNKNOWN',
    site: 'Global FFZ',
    original_name: 'UNKNOWN',
    width: 36,
    height: 30,
    aspect_ratio: 1.2,
  },
];
