name: 'Slack Deploy Notification'
description: 'Send deployment summary to Slack'

inputs:
  webhook_url:
    description: 'Slack incoming webhook URL'
    required: true
  version:
    description: 'App (native) version'
    required: true
  deployment_type:
    description: 'Deployment type (ota or native)'
    required: true
  tag:
    description: 'Release tag'
    required: true
  ios_update_id:
    description: 'iOS OTA update ID (OTA only)'
    required: false
    default: ''
  android_update_id:
    description: 'Android OTA update ID (OTA only)'
    required: false
    default: ''
  update_group_id:
    description: 'OTA update group ID (OTA only)'
    required: false
    default: ''
  previous_ios_update_id:
    description: 'Previous iOS OTA update ID (fallback when this run has no iOS id)'
    required: false
    default: ''
  previous_android_update_id:
    description: 'Previous Android OTA update ID (fallback when this run has no Android id)'
    required: false
    default: ''
  release_notes:
    description: 'Changelog / release notes text (fallback when release_notes_file not used)'
    required: false
    default: ''
  release_notes_file:
    description: 'Path to file containing full changelog markdown (overrides release_notes when present)'
    required: false
    default: ''
  release_url:
    description: 'URL to the GitHub release'
    required: false
    default: ''
  repository:
    description: 'GitHub repository (owner/repo)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build and send Slack message
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        VERSION: ${{ inputs.version }}
        DEPLOYMENT_TYPE: ${{ inputs.deployment_type }}
        TAG: ${{ inputs.tag }}
        IOS_UPDATE_ID: ${{ inputs.ios_update_id }}
        ANDROID_UPDATE_ID: ${{ inputs.android_update_id }}
        UPDATE_GROUP_ID: ${{ inputs.update_group_id }}
        PREVIOUS_IOS_UPDATE_ID: ${{ inputs.previous_ios_update_id }}
        PREVIOUS_ANDROID_UPDATE_ID: ${{ inputs.previous_android_update_id }}
        RELEASE_NOTES: ${{ inputs.release_notes }}
        RELEASE_NOTES_FILE: ${{ inputs.release_notes_file }}
        RELEASE_URL: ${{ inputs.release_url }}
        REPOSITORY: ${{ inputs.repository }}
      run: |
        set -e

        if [ -z "$WEBHOOK_URL" ] || [ "$WEBHOOK_URL" = "" ]; then
          echo "Slack webhook URL not set, skipping notification"
          exit 0
        fi

        # Prefer changelog from file (avoids job output truncation)
        if [ -n "$RELEASE_NOTES_FILE" ] && [ -f "$RELEASE_NOTES_FILE" ]; then
          RELEASE_NOTES=$(cat "$RELEASE_NOTES_FILE")
        fi

        # Keep only this release: take content up to the next "## " version header (exclude older versions / full changelog)
        if [ -n "$RELEASE_NOTES" ]; then
          RELEASE_NOTES=$(echo "$RELEASE_NOTES" | awk 'BEGIN{first=1} /^## / { if (!first) exit; first=0 } { print }')
        fi

        if [ "$DEPLOYMENT_TYPE" = "ota" ]; then
          HEADER_EMOJI="📦"
          HEADER_TEXT="Foam — OTA Update"
          IOS_DISPLAY="${IOS_UPDATE_ID:-$PREVIOUS_IOS_UPDATE_ID}"
          ANDROID_DISPLAY="${ANDROID_UPDATE_ID:-$PREVIOUS_ANDROID_UPDATE_ID}"
          [ -z "$IOS_DISPLAY" ] && IOS_DISPLAY="—"
          [ -z "$ANDROID_DISPLAY" ] && ANDROID_DISPLAY="—"
          VERSION_BLOCK="*Native app version:* \`${VERSION}\`
        *OTA Group:* \`${UPDATE_GROUP_ID}\`
        *iOS Update ID:* \`${IOS_DISPLAY}\`
        *Android Update ID:* \`${ANDROID_DISPLAY}\`"
        else
          HEADER_EMOJI="🔨"
          HEADER_TEXT="Foam — Native Build"
          VERSION_BLOCK="*Native version:* \`${VERSION}\` (tag: \`${TAG}\`)"
        fi

        # Changelog: short preview in mrkdwn (no code block), link to GitHub for full — "collapsible" style
        PREVIEW_LEN=1200
        CHANGELOG_PREVIEW="$RELEASE_NOTES"
        if [ ${#CHANGELOG_PREVIEW} -gt "$PREVIEW_LEN" ]; then
          CHANGELOG_PREVIEW="${CHANGELOG_PREVIEW:0:$((PREVIEW_LEN))}…"
        fi
        CHANGELOG_PREVIEW_JSON=$(printf '%s' "$CHANGELOG_PREVIEW" | jq -Rs .)
        RELEASE_URL_JSON=$(printf '%s' "$RELEASE_URL" | jq -Rs .)
        CHANGELOG_MRKDWN_JSON=$(jq -n \
          --argjson preview "$CHANGELOG_PREVIEW_JSON" \
          --argjson url "$RELEASE_URL_JSON" \
          '("*Changelog*" + (if $url != "" then " · <" + $url + "|View full on GitHub>\n\n" else "\n\n" end) + $preview + (if $url != "" then "\n\n<" + $url + "|View full changelog on GitHub>" else "" end))')

        FOOTER="Expo: <https://expo.dev|expo.dev>"
        [ -n "$REPOSITORY" ] && FOOTER="${FOOTER} | Repo: <https://github.com/${REPOSITORY}|${REPOSITORY}>"
        FOOTER_JSON=$(printf '%s' "$FOOTER" | jq -Rs .)
        VERSION_BLOCK_JSON=$(printf '%s' "$VERSION_BLOCK" | jq -Rs .)
        HEADER_JSON=$(printf '%s' "${HEADER_EMOJI} ${HEADER_TEXT}" | jq -Rs .)

        # Changelog section: optional "View on GitHub" button (collapsible-style link)
        if [ -n "$RELEASE_URL" ]; then
          PAYLOAD=$(jq -n \
            --argjson header "$HEADER_JSON" \
            --argjson version_block "$VERSION_BLOCK_JSON" \
            --argjson changelog_mrkdwn "$CHANGELOG_MRKDWN_JSON" \
            --argjson footer "$FOOTER_JSON" \
            --arg url "$RELEASE_URL" \
            '{
              blocks: [
                { type: "header", text: { type: "plain_text", text: $header, emoji: true } },
                { type: "section", text: { type: "mrkdwn", text: $version_block } },
                { type: "section", text: { type: "mrkdwn", text: $changelog_mrkdwn }, accessory: { type: "button", text: { type: "plain_text", text: "View on GitHub", emoji: true }, url: $url } },
                { type: "context", elements: [{ type: "mrkdwn", text: $footer }] }
              ]
            }')
        else
          PAYLOAD=$(jq -n \
            --argjson header "$HEADER_JSON" \
            --argjson version_block "$VERSION_BLOCK_JSON" \
            --argjson changelog_mrkdwn "$CHANGELOG_MRKDWN_JSON" \
            --argjson footer "$FOOTER_JSON" \
            '{
              blocks: [
                { type: "header", text: { type: "plain_text", text: $header, emoji: true } },
                { type: "section", text: { type: "mrkdwn", text: $version_block } },
                { type: "section", text: { type: "mrkdwn", text: $changelog_mrkdwn } },
                { type: "context", elements: [{ type: "mrkdwn", text: $footer }] }
              ]
            }')
        fi

        curl -sSf -X POST "$WEBHOOK_URL" \
          -H 'Content-Type: application/json' \
          -d "$PAYLOAD" || { echo "Slack notification failed"; exit 1; }
        echo "Slack notification sent."
