import { StyleSheet } from 'react-native';

import { theme } from '@app/styles/themes';

export const styles = StyleSheet.create({
  mediaCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(12, 12, 14, 0.94)',
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  mediaContainer: {
    flexBasis: '100%',
    marginVertical: 4,
    maxWidth: 260,
  },
  mediaEyebrow: {
    color: theme.color.brand.twitchBorder,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 12,
  },
  mediaEyebrowRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  mediaInfo: {
    flex: 1,
    gap: 2,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  mediaMeta: {
    color: theme.color.textSecondary.dark,
    fontSize: 11,
    lineHeight: 13,
  },
  mediaMetaSkeleton: {
    borderCurve: 'continuous',
    borderRadius: theme.radius.sm,
    height: 10,
    width: '48%',
  },
  mediaThumbnail: {
    height: '100%',
    width: '100%',
  },
  mediaThumbnailEmpty: {
    alignItems: 'center',
    backgroundColor: 'rgba(145, 71, 255, 0.18)',
    justifyContent: 'center',
  },
  mediaThumbnailFrame: {
    alignItems: 'center',
    backgroundColor: theme.colorBlack,
    flexShrink: 0,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 88,
  },
  mediaTitle: {
    color: theme.color.text.dark,
    fontSize: theme.fontSize12,
    fontWeight: '600',
    lineHeight: 15,
  },
  mediaTitleSkeleton: {
    borderCurve: 'continuous',
    borderRadius: theme.radius.sm,
    height: 13,
    width: '82%',
  },
  playBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    borderColor: 'rgba(255, 255, 255, 0.28)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 22,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -11,
    marginTop: -11,
    position: 'absolute',
    top: '50%',
    width: 22,
  },
  inlineChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderCurve: 'continuous',
    borderRadius: 6,
    flexDirection: 'row',
    gap: 4,
    maxWidth: '100%',
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  inlineThumbnail: {
    borderCurve: 'continuous',
    borderRadius: 4,
    height: 28,
    width: 28,
  },
  inlineTitle: {
    color: theme.color.text.dark,
    flexShrink: 1,
    fontSize: theme.fontSize12,
    lineHeight: 15,
    maxWidth: 140,
  },
  inlineTitleSkeleton: {
    borderCurve: 'continuous',
    borderRadius: 4,
    height: 12,
    width: 72,
  },
});
