import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixturePath = path.join(
  root,
  'src/components/Chat/components/ChatMessage/__fixtures__/sevenTvPaints.fixture.ts',
);

const PAINTS_QUERY = `query PaintsQuery {
  paints {
    paints {
      id
      name
      data {
        layers {
          id
          opacity
          ty {
            __typename
            ... on PaintLayerTypeLinearGradient {
              angle
              repeating
              stops { at color { r g b a } }
            }
            ... on PaintLayerTypeRadialGradient {
              repeating
              shape
              stops { at color { r g b a } }
            }
            ... on PaintLayerTypeSingleColor {
              color { r g b a }
            }
            ... on PaintLayerTypeImage {
              images { url mime size scale width height frameCount }
            }
          }
        }
        shadows { offsetX offsetY blur color { r g b a } }
      }
    }
  }
}`;

async function fetchAllPaints() {
  const res = await fetch('https://7tv.io/v4/gql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: PAINTS_QUERY }),
    signal: AbortSignal.timeout(30_000),
  });

  if (!res.ok) {
    throw new Error(`7TV GQL request failed: HTTP ${res.status}`);
  }

  const result = await res.json();
  if (result.errors?.length) {
    throw new Error(`7TV GQL: ${JSON.stringify(result.errors)}`);
  }

  const paints = result.data?.paints?.paints ?? [];
  // Sort by name so the fixture diffs stay stable between refreshes, matching
  // the ordering sevenTvService.fetchAllPaints() applies. Pin the locale so the
  // ordering is deterministic regardless of the machine's default locale.
  return [...paints].sort((a, b) => a.name.localeCompare(b.name, 'en'));
}

const paints = await fetchAllPaints();

const paintsJson = JSON.stringify(paints, null, 2)
  .replaceAll('"shape": "CIRCLE"', '"shape": PaintRadialGradientShape.Circle')
  .replaceAll(
    '"shape": "ELLIPSE"',
    '"shape": PaintRadialGradientShape.Ellipse',
  );

const fileContents =
  `import { PaintRadialGradientShape } from '@app/graphql/generated/gql';\n` +
  `import type { SevenTvPaintSource } from '@app/utils/color/sevenTvPaintData';\n\n` +
  `// Generated by scripts/refreshPaintFixtures.mjs — do not edit by hand.\n` +
  `export const sevenTvPaintsFixture: SevenTvPaintSource[] = ${paintsJson};\n`;

writeFileSync(fixturePath, fileContents);

console.log(
  `wrote ${paints.length} paints to ${path.relative(root, fixturePath)}`,
);
