name: Build
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
env:
  NODE_VERSION: 18.18.0

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
        
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    timeout-minutes: 20
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils
        
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: get yarn cache directory
        id: cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ./

      - name: setup yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
            path: ${{ steps.cache.outputs.dir }}
            key: yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                yarn-
                  
      - uses: actions/labeler@v4
        with:
          sync-labels: true

      - name: install yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Check commit message
        run: yarn commitlint --from=HEAD^1

      - name: format:check
        run: yarn format:check

      - name: lint
        run: yarn lint

      - name: jest
        run: yarn test

      - name: tsc
        run: yarn tsc

  preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: get yarn cache directory
        id: cache
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ./

      - name: setup yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
            path: ${{ steps.cache.outputs.dir }}
            key: yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                yarn-
                  
      - uses: actions/labeler@v4
        with:
          sync-labels: true

      - name: install yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn
      
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.FOAM_RELEASE_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.FOAM_RELEASE_TOKEN }}
      
      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch=pr-${{ github.event.number }}
          github-token: ${{ secrets.FOAM_GITHUB_TOKEN }}
          qr-target: expo-go

      # - name: Setup Expo
      #   uses: expo/expo-github-action@v7
      #   with:
      #     expo-version: latest
      #     eas-version: latest
      #     token: ${{ secrets.FOAM_RELEASE_TOKEN }}

      # - name: Setup EAS
      #   uses: expo/expo-github-action@v8
      #   with:
      #     eas-version: latest
      #     token: ${{ secrets.FOAM_RELEASE_TOKEN }}

      # - name: Create preview
      #   uses: expo/expo-github-action/preview@v8
      #   with:
      #     command: eas update --branch preview --message "test"
      #     comment: true
      #     github-token: ${{ secrets.FOAM_GITHUB_TOKEN }}
      #     qr-target: expo-go
