name: Commitlint
on:
  pull_request:
permissions:
  contents: read
jobs:
  cz:
    name: cz
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: 🥟 Setup Bun and install dependencies
        uses: ./.github/actions/setup-bun-install
        with:
          node: 'true'
          ignore-scripts: 'true'

      - name: 🧑‍🔬 Check commit message
        run: |
          bun run commitlint --from=HEAD^1
