name: EAS app deployment
on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'App variant to build/deploy'
        required: true
        type: choice
        default: 'production'
        options:
          - production
          - testflight
          - internal
      platform:
        description: 'The platform to deploy to'
        required: true
        type: choice
        default: 'all'
        options:
          - all
          - ios
          - android
jobs:
  app_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: eas-deploy-fingerprint-main
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: src/foam
    steps:
      - name: 🔎 Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/tutorial/eas/using-github/"
            exit 1
          fi

      - name: 🏗 Setup repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: 🥟 Setup Bun and install dependencies
        uses: ./.github/actions/setup-bun-install
        with:
          node: 'true'
          ignore-scripts: 'true'

      - name: Λ Setup EAS
        if: ${{ !inputs.dry }}
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun
          patch-watchers: false

      - name: 🚀 Build & deploy
        run: |
          if [ "${{ inputs.platform }}" == "all" ]; then
            bun run build:${{ inputs.variant }}:ios
            bun run build:${{ inputs.variant }}:android

          elif [ "${{ inputs.platform }}" == "ios" ]; then
            bun run build:${{ inputs.variant }}:ios

          elif [ "${{ inputs.platform }}" == "android" ]; then
            bun run build:${{ inputs.variant }}:android
          fi
