name: Label
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 🏷️ Apply path-based labels
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          sync-labels: true
