name: Check ESLint
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: 🥟 Setup Bun and install dependencies
        uses: ./.github/actions/setup-bun-install
        with:
          node: 'true'

      - name: 🤓 Run ESLint
        run: bun run lint
