name: Lookup Cached Debug Build
on:
  workflow_call:
    inputs:
      platform:
        description: 'The platform for which the build should be looked up (android | ios)'
        required: true
        type: string
    outputs:
      build-exists:
        description: 'Whether the build exists in the cache'
        value: ${{ jobs.lookup-cached-build.outputs.build-exists }}
      fingerprint:
        description: 'The fingerprint of the native code'
        value: ${{ jobs.lookup-cached-build.outputs.fingerprint }}

jobs:
  lookup-cached-build:
    name: Lookup cached debug build
    runs-on: ubuntu-latest
    outputs:
      build-exists: ${{ steps.debug-build-restore.outputs.cache-hit }}
      fingerprint: ${{ steps.fingerprint.outputs.fingerprint }}
    steps:
      - name: 🔍 Validate inputs
        run: |
          if [[ "${{ inputs.platform }}" != "android" && "${{ inputs.platform }}" != "ios" ]]; then
            echo "Invalid platform: ${{ inputs.platform }}. Must be one of: android, ios."
            exit 1
          else
            echo "Valid platform specified: ${{ inputs.platform }}"
          fi

      - name: 🏗 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🧬 Calculate fingerprint
        id: fingerprint
        run: |
          FINGERPRINT=$(bun run fingerprint:${{ inputs.platform }} | grep '^fingerprint:' | cut -d ' ' -f2-)
          echo "Fingerprint for ${{ inputs.platform }}: $FINGERPRINT"
          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV
          echo "fingerprint=$FINGERPRINT" >> $GITHUB_OUTPUT
        
      - name: 🐛 Try to restore build from cache
        id: debug-build-restore
        uses: actions/cache/restore@v4
        with:
          lookup-only: true
          path: ${{ inputs.platform }}-debug-build/
          key: ${{ inputs.platform }}-debug-build-${{ env.FINGERPRINT }}
