name: Check self hosted runner
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  self-hosted-runner:
    name: ESLint
    runs-on: foam
    if: github.repository == 'luke-h1/foam' && (github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'self-hosted-test'))
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: 🥟 Setup Bun and install dependencies
        uses: ./.github/actions/setup-bun-install
        with:
          node: 'true'

      - name: 🤓 Run ESLint
        run: bun run lint
